import { IconType } from "react-icons";
import { BsFillFileEarmarkPersonFill } from "react-icons/bs";
import { AiFillMail} from "react-icons/ai";

import { 
  FaNodeJs,
  FaHtml5,
  FaDocker,
  FaJava,
  FaLinux,
  FaFileAlt,
} from "react-icons/fa";

import { GrMysql } from "react-icons/gr";

import { LiaGoogle } from "react-icons/lia";


import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineCodeBracket,
  HiMiniCodeBracket,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiSmileyMehDuotone,
  PiMoonDuotone,
  PiSunDuotone,
  PiGameControllerDuotone,
  PiAcornDuotone,
  PiPencilCircleDuotone,
  PiPencilDuotone,
} from "react-icons/pi";

import { 
  FcBusinessman,
  FcCustomerSupport,
  FcCircuit,
  FcBookmark,
  FcDepartment,
  FcChargeBattery,
  FcCloseUpMode,
  FcShop,
  FcManager,
  FcMindMap,
  FcFlowChart,
  FcOrgUnit,
  FcHome,
  FcNightLandscape,
  FcLandscape,
  FcPuzzle,
  FcPicture,
  FcStackOfPhotos,
  FcReading,
  FcDocument,
 } from "react-icons/fc";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiThreedotjs,
  SiFastapi,
  SiLangchain,
  SiLatex,
  SiTensorflow,
  SiGooglecolab,
  SiMediapipe,
  SiOpencv,
  SiScikitlearn,
  SiPytorch,
  SiGooglegemini,
  SiGooglecalendar,
  SiGooglemeet,
  SiPostman,
  SiJira,
  SiArxiv,
} from "react-icons/si";

import { 
  FaDiscord, 
  FaGithub, 
  FaLinkedin, 
  FaX, 
  FaThreads, 
  FaInstagram, 
  FaXTwitter, 
  FaFacebook, 
  FaPinterest, 
  FaWhatsapp, 
  FaReddit, 
  FaTelegram, 
  FaFilePdf,
  FaFile,
  FaRedditAlien,
  FaGoogleScholar,
  FaRegFaceMeh,
} from "react-icons/fa6";
import { gallery, playground } from "./content";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  threejs: SiThreedotjs,
  nodejs: FaNodeJs,
  html5: FaHtml5,
  fastapi: SiFastapi,
  langchain: SiLangchain,
  latex: SiLatex,
  docker: FaDocker,
  tensorflow: SiTensorflow,
  colab: SiGooglecolab,
  mediapipe: SiMediapipe,
  opencv: SiOpencv,
  java: FaJava,
  scikitlearn: SiScikitlearn,
  pytorch: SiPytorch,
  gemini: SiGooglegemini,
  linux: FaLinux,
  postman: SiPostman,
  jira: SiJira,
  sql: GrMysql ,
  pdf: FaFilePdf,
  file: FaFileAlt,
  resume: BsFillFileEarmarkPersonFill,
  mail: AiFillMail,
  googleCalendar: SiGooglecalendar,
  googleMeet: SiGooglemeet,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaRedditAlien,
  telegram: FaTelegram,
  instagram: FaInstagram,
  code: HiMiniCodeBracket,
  arxiv: SiArxiv,
  googlescholar: FaGoogleScholar,
  face: PiSmileyMehDuotone,
  face2: FcManager,
  grid2: FcOrgUnit,
  book2: FcDocument,
  home2: FcHome,
  dark2: FcNightLandscape,
  dark1: PiMoonDuotone,
  light2: FcLandscape,
  light1: PiSunDuotone,
  playground: PiGameControllerDuotone,
  playground2: FcPuzzle,
  gallery2: FcCloseUpMode,
  learning: PiAcornDuotone,
  learning2: FcReading,
  pencil: PiPencilDuotone,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
